### ISSUE TITLE
error during runonce (Contao 4.7)

### ISSUE THREAD

**Issue by fritzmg** [BugBuster1701/contao-botdetection-bundle#26]
The following error happens when installing this extension and then opening the install tool under Contao 4.7:

```
ErrorException: fopen(/var/cache/prod/botdetection/desbma.txt): failed to open stream: No such file or directory
#18 vendor/bugbuster/contao-botdetection-bundle/src/Resources/contao/classes/Referrer/ProviderCommunication.php(117): handleError
#17 vendor/sentry/sentry/lib/Raven/ErrorHandler.php(0): fopen
#16 vendor/bugbuster/contao-botdetection-bundle/src/Resources/contao/classes/Referrer/ProviderCommunication.php(117): loadProviderFiles
#15 vendor/bugbuster/contao-botdetection-bundle/src/Resources/contao/config/runonce.php(47): run
#14 vendor/bugbuster/contao-botdetection-bundle/src/Resources/contao/config/runonce.php(129): include
#13 vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php(266): handleRunOnce
#12 vendor/contao/installation-bundle/src/InstallTool.php(304): handleRunOnce
#11 vendor/contao/installation-bundle/src/Controller/InstallationController.php(418): adjustDatabaseTables
#10 vendor/contao/installation-bundle/src/Controller/InstallationController.php(99): installAction
#9 vendor/symfony/http-kernel/HttpKernel.php(150): handleRaw
#8 vendor/symfony/http-kernel/HttpKernel.php(67): handle
#7 vendor/symfony/http-kernel/Kernel.php(198): handle
#6 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): handle
#5 vendor/symfony/http-kernel/HttpCache/HttpCache.php(448): forward
#4 vendor/symfony/framework-bundle/HttpCache/HttpCache.php(57): forward
#3 vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): pass
#2 vendor/symfony/http-kernel/HttpCache/HttpCache.php(183): handle
#1 vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(98): handle
#0 web/app.php(58): null
```

I only noticed this via sentry though.

**Comment by BugBuster1701** [comment]
Was the directory `/var/cache/prod/botdetection` created?

**Comment by fritzmg** [comment]
No, the directory was not created. Since this happens during the processing of the `runonce.php` files, I think the error message is usually ignored and thus only visible with something like the Sentry Bundle. May be it can be ignored in general, but I wanted to report it anyway :)
